--------------------------------------------------------
--  Fichier créé - mardi-novembre-02-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HEBERGEMENT
--------------------------------------------------------

  CREATE TABLE "FAKHRI"."HEBERGEMENT" 
   (	"ID_HEBERGEMENT" NUMBER(*,0), 
	"NOM_HEBERGEMENT" VARCHAR2(20 BYTE), 
	"ADRESSE_HEBERGEMENT" VARCHAR2(20 BYTE), 
	"NBRE_ETOILES" NUMBER(*,0), 
	"NBRE_CHAMBRES" NUMBER(*,0), 
	"NOTE_HEBERGEMENT" NUMBER(*,0), 
	"ID_STADE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FAKHRI.HEBERGEMENT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index HEBERGEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAKHRI"."HEBERGEMENT_PK" ON "FAKHRI"."HEBERGEMENT" ("ID_HEBERGEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table HEBERGEMENT
--------------------------------------------------------

  ALTER TABLE "FAKHRI"."HEBERGEMENT" ADD CONSTRAINT "HEBERGEMENT_PK" PRIMARY KEY ("ID_HEBERGEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
